// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WppSender.Infrastructure.Persistence;

#nullable disable

namespace WppSender.Infrastructure.Migrations
{
    [DbContext(typeof(WppSenderDbContext))]
    [Migration("20260801232849_AddGruposTable")]
    partial class AddGruposTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WppSender.Domain.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rua");

                    b.HasKey("Id")
                        .HasName("pk_enderecos");

                    b.ToTable("enderecos", (string)null);
                });

            modelBuilder.Entity("WppSender.Domain.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_grupos");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("WppSender.Domain.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("uuid")
                        .HasColumnName("endereco_id");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Instagram")
                        .HasColumnType("text")
                        .HasColumnName("instagram");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Origem")
                        .HasColumnType("text")
                        .HasColumnName("origem");

                    b.Property<string>("TelefoneNormalizado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasIndex("EnderecoId")
                        .HasDatabaseName("ix_leads_endereco_id");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_leads_grupo_id");

                    b.HasIndex("TelefoneNormalizado")
                        .IsUnique()
                        .HasDatabaseName("uq_leads_telefone_ativo")
                        .HasFilter("deletado_em IS NULL");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("WppSender.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("WppSender.Domain.Lead", b =>
                {
                    b.HasOne("WppSender.Domain.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .HasConstraintName("fk_leads_enderecos_endereco_id");

                    b.HasOne("WppSender.Domain.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_leads_grupos_grupo_id");

                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
