// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WppSender.Infrastructure.Persistence;

#nullable disable

namespace WppSender.Infrastructure.Migrations
{
    [DbContext(typeof(WppSenderDbContext))]
    [Migration("20260805154739_AddConcluidaComFalhas")]
    partial class AddConcluidaComFalhas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WppSender.Domain.Campanha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AgendadoPara")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("agendado_para");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<int>("IntervaloMaxSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("intervalo_max_segundos");

                    b.Property<int>("IntervaloMinSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("intervalo_min_segundos");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_campanhas");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_campanhas_grupo_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_campanhas_status");

                    b.ToTable("campanhas", null, t =>
                        {
                            t.HasCheckConstraint("ck_campanhas_status", "status IN ('rascunho','agendada','em_andamento','pausada','concluida','concluida_com_falhas','cancelada')");
                        });
                });

            modelBuilder.Entity("WppSender.Domain.ConfiguracaoEnvio", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateOnly>("DataReferencia")
                        .HasColumnType("date")
                        .HasColumnName("data_referencia");

                    b.Property<int>("EnviosRealizadosHoje")
                        .HasColumnType("integer")
                        .HasColumnName("envios_realizados_hoje");

                    b.Property<int>("LimiteDiarioEnvios")
                        .HasColumnType("integer")
                        .HasColumnName("limite_diario_envios");

                    b.HasKey("Id")
                        .HasName("pk_configuracao_envio");

                    b.ToTable("configuracao_envio", null, t =>
                        {
                            t.HasCheckConstraint("ck_configuracao_envio_id", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            DataReferencia = new DateOnly(2020, 1, 1),
                            EnviosRealizadosHoje = 0,
                            LimiteDiarioEnvios = 120
                        });
                });

            modelBuilder.Entity("WppSender.Domain.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rua");

                    b.HasKey("Id")
                        .HasName("pk_enderecos");

                    b.ToTable("enderecos", (string)null);
                });

            modelBuilder.Entity("WppSender.Domain.Envio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("CampanhaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campanha_id");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("WhatsAppMensagemId")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp_mensagem_id");

                    b.HasKey("Id")
                        .HasName("pk_campanha_envios");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_campanha_envios_lead_id");

                    b.HasIndex("CampanhaId", "LeadId")
                        .IsUnique()
                        .HasDatabaseName("ix_campanha_envios_campanha_id_lead_id");

                    b.HasIndex("CampanhaId", "Status")
                        .HasDatabaseName("ix_campanha_envios_campanha_id_status");

                    b.ToTable("campanha_envios", null, t =>
                        {
                            t.HasCheckConstraint("ck_campanha_envios_status", "status IN ('pendente','enviado','entregue','lido','falhou','falhou_entrega')");
                        });
                });

            modelBuilder.Entity("WppSender.Domain.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_grupos");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("WppSender.Domain.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("uuid")
                        .HasColumnName("endereco_id");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Instagram")
                        .HasColumnType("text")
                        .HasColumnName("instagram");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Origem")
                        .HasColumnType("text")
                        .HasColumnName("origem");

                    b.Property<string>("TelefoneNormalizado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_leads_criado_em");

                    b.HasIndex("EnderecoId")
                        .HasDatabaseName("ix_leads_endereco_id");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_leads_grupo_id");

                    b.HasIndex("TelefoneNormalizado")
                        .IsUnique()
                        .HasDatabaseName("uq_leads_telefone_ativo")
                        .HasFilter("deletado_em IS NULL");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("WppSender.Domain.SessaoWhatsApp", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_whatsapp_sessao");

                    b.ToTable("whatsapp_sessao", null, t =>
                        {
                            t.HasCheckConstraint("ck_whatsapp_sessao_status", "status IN ('desconectado','aguardando_qr','conectado')");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Status = "desconectado"
                        });
                });

            modelBuilder.Entity("WppSender.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("WppSender.Domain.Envio", b =>
                {
                    b.HasOne("WppSender.Domain.Campanha", null)
                        .WithMany()
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campanha_envios_campanhas_campanha_id");
                });

            modelBuilder.Entity("WppSender.Domain.Lead", b =>
                {
                    b.HasOne("WppSender.Domain.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .HasConstraintName("fk_leads_enderecos_endereco_id");

                    b.HasOne("WppSender.Domain.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_leads_grupos_grupo_id");

                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
